In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('data/data_processing.csv')

converting the data to the desired type

In [6]:
data.head()

Unnamed: 0 Manufacturer    Model  Sales_in_thousands  __year_resale_value  \
0           0        Acura  Integra              16.919               16.360   
1           1        Acura       TL              39.384               19.875   
2           2        Acura       CL              14.114               18.225   
3           3        Acura       RL               8.588               29.725   
4           4         Audi       A4              20.397               22.255   

  Vehicle_type  Price_in_thousands  Engine_size  Horsepower  Wheelbase  Width  \
0    Passenger             21.5000          1.8       140.0      101.2   67.3   
1    Passenger             28.4000          3.2       225.0      108.1   70.3   
2    Passenger             35.8734          3.2       225.0      106.9   70.6   
3    Passenger             42.0000          3.5       210.0      114.6   71.4   
4    Passenger             23.9900          1.8       150.0      102.6   68.2   

   Length  Curb_weight  Fuel_capacity  Fuel_efficiency Latest_Launch  \
0   172.4        2.639           13.2             28.0      2/2/2012   
1   192.9        3.517           17.2             25.0      6/3/2011   
2   192.0        3.470           17.2             26.0      1/4/2012   
3   196.6        3.850           18.0             22.0     3/10/2011   
4   178.0        2.998           16.4             27.0     10/8/2011   

   Power_perf_factor  
0          58.280150  
1          91.370778  
2          93.352703  
3          91.389779  
4          62.777639

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           156 non-null    int64  
 1   Manufacturer         156 non-null    object 
 2   Model                156 non-null    object 
 3   Sales_in_thousands   156 non-null    float64
 4   __year_resale_value  156 non-null    float64
 5   Vehicle_type         156 non-null    object 
 6   Price_in_thousands   156 non-null    float64
 7   Engine_size          156 non-null    float64
 8   Horsepower           156 non-null    float64
 9   Wheelbase            156 non-null    float64
 10  Width                156 non-null    float64
 11  Length               156 non-null    float64
 12  Curb_weight          156 non-null    float64
 13  Fuel_capacity        156 non-null    float64
 14  Fuel_efficiency      156 non-null    float64
 15  Latest_Launch        156 non-null    obj

in this case, the numeric columns have already been converted to the desired type, 
if this were not the case, we would have converted from the object type to the float64 or int type

although we have an object column with dates, there is no point in converting it to datetime, 
because when saving data to csv, it does not play any role, it will be the same object

In [10]:
data['Fuel_efficiency'].unique()

array([28. , 25. , 26. , 22. , 27. , 21. , 24. , 23. , 15. , 33. , 45. ,
       29. , 16. , 17. , 19. , 30. , 18. , 32. , 31. , 20. , 22.8])

In [11]:
data['Horsepower'].nunique()

66

In [12]:
data['Horsepower'].unique()

array([140., 225., 210., 150., 200., 310., 170., 193., 175., 240., 205.,
       275., 255., 115., 180., 345., 120.,  55., 163., 168., 132., 253.,
       202., 450., 230., 110., 190., 155., 107., 119., 220., 106., 135.,
       146.,  92., 148., 227., 195., 300., 290., 215., 113., 154., 145.,
       161., 173., 125., 153., 185., 221., 302., 126., 222., 250., 217.,
       100., 124., 137., 165., 133., 142., 194., 127., 160., 236., 201.])

In [15]:
(data['Horsepower'] % 1 == 0).unique()

array([ True])

In [16]:
data['Horsepower'] = data['Horsepower'].astype(int)

In [17]:
data.head()

Unnamed: 0 Manufacturer    Model  Sales_in_thousands  __year_resale_value  \
0           0        Acura  Integra              16.919               16.360   
1           1        Acura       TL              39.384               19.875   
2           2        Acura       CL              14.114               18.225   
3           3        Acura       RL               8.588               29.725   
4           4         Audi       A4              20.397               22.255   

  Vehicle_type  Price_in_thousands  Engine_size  Horsepower  Wheelbase  Width  \
0    Passenger             21.5000          1.8         140      101.2   67.3   
1    Passenger             28.4000          3.2         225      108.1   70.3   
2    Passenger             35.8734          3.2         225      106.9   70.6   
3    Passenger             42.0000          3.5         210      114.6   71.4   
4    Passenger             23.9900          1.8         150      102.6   68.2   

   Length  Curb_weight  Fuel_capacity  Fuel_efficiency Latest_Launch  \
0   172.4        2.639           13.2             28.0      2/2/2012   
1   192.9        3.517           17.2             25.0      6/3/2011   
2   192.0        3.470           17.2             26.0      1/4/2012   
3   196.6        3.850           18.0             22.0     3/10/2011   
4   178.0        2.998           16.4             27.0     10/8/2011   

   Power_perf_factor  
0          58.280150  
1          91.370778  
2          93.352703  
3          91.389779  
4          62.777639

In [18]:
(data['Fuel_efficiency'] % 1 == 0).unique()

array([ True, False])

In [19]:
data['Vehicle_type'].unique()

array(['Passenger', 'Car'], dtype=object)

In [23]:
data.drop(columns='Unnamed: 0', axis=1, inplace=True)

we will not do ranking

In [26]:
data.to_csv('data/data_end.csv', index=False)